kind: Pod 
apiVersion: v1 
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources: 
    # soft limit
      requests:
        cpu: 100m
        memory: 128mi
    # limit should be atleast or more than the requests i.e Hard limit
      limits:
        cpu: 100m
        memory: 128mi