kind: Pod 
apiVersion: v1 
metadata: 
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
      - configMapKeyRef:
          name: daws78

      
      
      # - name: course
      #   valueFrom: 
      #     configMapKeyRef:
      #       key: course
      #       name: daws78
      # - name: trainer 
      #   valueFrom:
      #     configMapKeyRef:
      #       key: trainer
      #       name: daws78