kind: Pod 
apiVersion: v1
metadata: 
  name: nginx
  labels:
    name: frontend
    project: expense
    environment: dev
    component: frontend
spec:
  containers:
  - name: nginx
    image: nginx

