kind: Service
apiVersion: v1
metadata:
  name: nginx-np

spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    environment: dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #target port
    nodePort: 32760
