apiVersion: v1 
kind: ReplicaSet
metadata:
  name: nginx
  # these labels are related to replica set resources
  labels:
    app: nginx
    tier: frontend
  # modify replicas according to your case
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
    # below is the pod defination
  template: 
    metadata:
      labels:
        app: nginx
        tier: frontend
        project: some-project
    spec:
      containers:
      - name: nginx
        image: nginx 



